# Generated by Django 5.0.1 on 2024-02-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('date_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojaapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenando_por', models.CharField(max_length=200)),
                ('endereco_envio', models.CharField(max_length=20)),
                ('telefone', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('pedido_status', models.CharField(choices=[('Pedido Reecebido', 'Pedido Reecebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completo', 'Pedido Completo'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='produtos')),
                ('preco_mercado', models.PositiveIntegerField()),
                ('venda', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('garantia', models.CharField(blank=True, max_length=300, null=True)),
                ('return_devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='CarroPoroduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.produto')),
            ],
        ),
    ]
